config/routes.rb
Rails.application.routes.draw do
  resources :caiwuhuizongs
  resources :jichucanshus
  resources :fengkongcanshus
  resources :tuiguangxiangqings
  resources :xiaoxiliebiaos
  resources :xiaoximobans
  resources :dizhiguanlis
  resources :jiaoseguanlis
  resources :quanxianguanlis
  resources :guanliyuans
  resources :dakuanshibais
  resources :yifangkuans
  resources :xujiedaifangkuanliebiaos
  resources :xinyonghudaifangkuanliebiaos
  resources :tuiguangs
  resources :dianhuahuangyes
  resources :fengxianguanlis
  resources :huiyuans
  resources :lcbzhiyawus
  resources :lcbzhanghus
  resources :kaiguans
  resources :lvmaotongs
  resources :webceshis
  resources :ceshijilus
  resources :pingguoceshis
  resources :anzhuoceshis
  resources :anzhuozidonghuaceshis
  resources :jiaobenzhixings
  resources :esjiaobens
  resources :xitongzhanghuguanlis
  resources :shujukusqlguanlis
  resources :shujukujiaobens
  resources :changyongzuoye1s
  resources :dengluzhanghus
  resources :shujufenxis
  resources :ceshirenwuguanlis
  resources :pingguodingshirenwus
  resources :shujukuzhanghus
  resources :dingshirenwus
  resources :changyongzuoyes
  resources :kuaisuzhixingsqljiaobens
  resources :kuaisufenfawenjians
  resources :kuaisujiaobenzhixings
  resources :pingguozhanghaos
  resources :ipdizhis
  resources :sousuos
  resources :umengs
  resources :shoujis
  resources :shuabangs
  resources :sslzhengshus
  resources :wifidns
  resources :androidupdates
  resources :menus
  resources :menuindices
  resources :peizhiguanlis
  resources :dns
  resources :yumings
  resources :jiankongs
  resources :feiyongs
  resources :mimas
  resources :fuwus
  resources :apps
  resources :diannaos
  get "/" => redirect("/menus")
  post 'login', :to => 'dengluzhanghus#login'
  get 'upload', :to => 'upload#index'
  post 'upload', :to => 'upload#upload'
  #get '/login' => 'dengluzhanghus#login1', :as => "menus"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/datafile.rb
class Datafile < ActiveRecord::Base  
  def self.save(upload)  
    #name =  upload['datafile'].original_filename  
    directory = "public/data"  
    # create the file path  
    path = File.join(directory, "aaa")  
    # write the file  
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }  
  end  
end  

app/models/diannao.rb
class Diannao < ApplicationRecord
has_and_belongs_to_many :Jiaobenzhixings
has_and_belongs_to_many :kuaisufenfawenjians

accepts_nested_attributes_for :Jiaobenzhixings, allow_destroy: true
def to_s
  mingzi.to_s+"_"+ip.to_s
end
end

app/models/dn.rb
class Dn < ApplicationRecord
end

app/models/feiyong.rb
class Feiyong < ApplicationRecord
end

app/models/fuwu.rb
class Fuwu < ApplicationRecord
end

app/models/huiyuan.rb
class Huiyuan < ApplicationRecord
end

app/models/ipdizhi.rb
class Ipdizhi < ApplicationRecord
end

app/models/jiankong.rb
class Jiankong < ApplicationRecord
end

app/models/kaiguan.rb
class Kaiguan < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :submenu, class_name: "menu",
                          foreign_key: "menu_id"
 
#  belongs_to :pmenu, class_name: "menu"
end

app/models/mima.rb
class Mima < ApplicationRecord
end

app/models/shouji.rb
class Shouji < ApplicationRecord
end

app/models/shuabang.rb
class Shuabang < ApplicationRecord
end

app/models/shujukujiaoben.rb
class Shujukujiaoben < ApplicationRecord
end

app/models/sousuo.rb
class Sousuo < ApplicationRecord
end

app/models/submenu.rb
class Submenu < Menu
end

app/models/tuiguang.rb
class Tuiguang < ApplicationRecord
end

app/models/umeng.rb
class Umeng < ApplicationRecord
end

app/models/wifidn.rb
class Wifidn < ApplicationRecord
end

app/models/yuming.rb
class Yuming < ApplicationRecord
end

app/controllers/shujukujiaobens_controller.rb
class ShujukujiaobensController < ApplicationController
  before_action :set_shujukujiaoben, only: [:index,:show, :edit, :update, :destroy]

  # GET /shujukujiaobens
  # GET /shujukujiaobens.json
  def index
    @shujukujiaobens = Shujukujiaoben.all
  end

  # GET /shujukujiaobens/1
  # GET /shujukujiaobens/1.json
  def show
  end

  # GET /shujukujiaobens/new
  def new
    @shujukujiaoben = Shujukujiaoben.new
  end

  # GET /shujukujiaobens/1/edit
  def edit
  end

  # POST /shujukujiaobens
  # POST /shujukujiaobens.json
  def create
    @shujukujiaoben = Shujukujiaoben.new(shujukujiaoben_params)

    respond_to do |format|
      if @shujukujiaoben.save
        format.html { redirect_to @shujukujiaoben, notice: 'Shujukujiaoben was successfully created.' }
        format.json { render :show, status: :created, location: @shujukujiaoben }
      else
        format.html { render :new }
        format.json { render json: @shujukujiaoben.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shujukujiaobens/1
  # PATCH/PUT /shujukujiaobens/1.json
  def update
    respond_to do |format|
      if @shujukujiaoben.update(shujukujiaoben_params)
        format.html { redirect_to @shujukujiaoben, notice: 'Shujukujiaoben was successfully updated.' }
        format.json { render :show, status: :ok, location: @shujukujiaoben }
      else
        format.html { render :edit }
        format.json { render json: @shujukujiaoben.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shujukujiaobens/1
  # DELETE /shujukujiaobens/1.json
  def destroy
    @shujukujiaoben.destroy
    respond_to do |format|
      format.html { redirect_to shujukujiaobens_url, notice: 'Shujukujiaoben was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

      @shujukujiaoben = Shujukujiaoben.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shujukujiaoben_params
      params.require(:shujukujiaoben).permit(:jiaobenmingcheng, :shujuquzhanghao, :mubiaojiqi, :buzhoumingcheng, :jiaobenlaiyuan, :jiaobenneirong, :caoshishijian)
    end
end

app/helpers/shujukujiaobens_helper.rb
module ShujukujiaobensHelper
end

app/views/shujukujiaobens/_form.html.erb
<%= form_for(shujukujiaoben) do |f| %>
  <% if shujukujiaoben.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shujukujiaoben.errors.count, "error") %> prohibited this shujukujiaoben from being saved:</h2>

      <ul>
      <% shujukujiaoben.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    脚本名称
    <%= f.text_field :jiaobenmingcheng %>
  </div>

  <div class="field">
    数据库账号
    <%= f.text_field :shujuquzhanghao %>
  </div>

  <div class="field">
    目标机器
    <%= f.text_field :mubiaojiqi %>
  </div>

  <div class="field">
    部首名称
    <%= f.text_field :buzhoumingcheng %>
  </div>

  <div class="field">
    脚本来源
    <%= f.text_field :jiaobenlaiyuan %>
  </div>

  <div class="field">
    脚本内容
    <%= f.text_field :jiaobenneirong %>
  </div>

  <div class="field">
    考试时间
    <%= f.text_field :caoshishijian %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shujukujiaobens/edit.html.erb
<h1>编辑数据库脚本</h1>

<%= render 'form', shujukujiaoben: @shujukujiaoben %>

<%= link_to 'Show', @shujukujiaoben %> |
<%= link_to 'Back', shujukujiaobens_path %>

app/views/shujukujiaobens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>数据库脚本</h1>

<table>
  <thead>
    <tr>
      <th>脚本名称</th>
      <th>数据库账号</th>
      <th>目标机器</th>
      <th>部首名称</th>
      <th>脚本来源</th>
      <th>脚本内容</th>
      <th>考试时间</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shujukujiaobens.each do |shujukujiaoben| %>
      <tr>
        <td><%= shujukujiaoben.jiaobenmingcheng %></td>
        <td><%= shujukujiaoben.shujuquzhanghao %></td>
        <td><%= shujukujiaoben.mubiaojiqi %></td>
        <td><%= shujukujiaoben.buzhoumingcheng %></td>
        <td><%= shujukujiaoben.jiaobenlaiyuan %></td>
        <td><%= shujukujiaoben.jiaobenneirong %></td>
        <td><%= shujukujiaoben.caoshishijian %></td>
        <td><%= link_to 'Show', shujukujiaoben %></td>
        <td><%= link_to 'Edit', edit_shujukujiaoben_path(shujukujiaoben) %></td>
        <td><%= link_to 'Destroy', shujukujiaoben, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建数据库脚本', new_shujukujiaoben_path %>

app/views/shujukujiaobens/new.html.erb
<h1>新建数据库脚本</h1>

<%= render 'form', shujukujiaoben: @shujukujiaoben %>

<%= link_to 'Back', shujukujiaobens_path %>

app/views/shujukujiaobens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>脚本名称:</strong>
  <%= @shujukujiaoben.jiaobenmingcheng %>
</p>

<p>
  <strong>数据库账号:</strong>
  <%= @shujukujiaoben.shujuquzhanghao %>
</p>

<p>
  <strong>目标机器:</strong>
  <%= @shujukujiaoben.mubiaojiqi %>
</p>

<p>
  <strong>部首名称:</strong>
  <%= @shujukujiaoben.buzhoumingcheng %>
</p>

<p>
  <strong>脚本来源:</strong>
  <%= @shujukujiaoben.jiaobenlaiyuan %>
</p>

<p>
  <strong>脚本内容:</strong>
  <%= @shujukujiaoben.jiaobenneirong %>
</p>

<p>
  <strong>考试时间:</strong>
  <%= @shujukujiaoben.caoshishijian %>
</p>

<%= link_to 'Edit', edit_shujukujiaoben_path(@shujukujiaoben) %> |
<%= link_to 'Back', shujukujiaobens_path %>