config/routes.rb
Rails.application.routes.draw do
  resources :caiwuhuizongs
  resources :jichucanshus
  resources :fengkongcanshus
  resources :tuiguangxiangqings
  resources :xiaoxiliebiaos
  resources :xiaoximobans
  resources :dizhiguanlis
  resources :jiaoseguanlis
  resources :quanxianguanlis
  resources :guanliyuans
  resources :dakuanshibais
  resources :yifangkuans
  resources :xujiedaifangkuanliebiaos
  resources :xinyonghudaifangkuanliebiaos
  resources :tuiguangs
  resources :dianhuahuangyes
  resources :fengxianguanlis
  resources :huiyuans
  resources :lcbzhiyawus
  resources :lcbzhanghus
  resources :kaiguans
  resources :lvmaotongs
  resources :webceshis
  resources :ceshijilus
  resources :pingguoceshis
  resources :anzhuoceshis
  resources :anzhuozidonghuaceshis
  resources :jiaobenzhixings
  resources :esjiaobens
  resources :xitongzhanghuguanlis
  resources :shujukusqlguanlis
  resources :shujukujiaobens
  resources :changyongzuoye1s
  resources :dengluzhanghus
  resources :shujufenxis
  resources :ceshirenwuguanlis
  resources :pingguodingshirenwus
  resources :shujukuzhanghus
  resources :dingshirenwus
  resources :changyongzuoyes
  resources :kuaisuzhixingsqljiaobens
  resources :kuaisufenfawenjians
  resources :kuaisujiaobenzhixings
  resources :pingguozhanghaos
  resources :ipdizhis
  resources :sousuos
  resources :umengs
  resources :shoujis
  resources :shuabangs
  resources :sslzhengshus
  resources :wifidns
  resources :androidupdates
  resources :menus
  resources :menuindices
  resources :peizhiguanlis
  resources :dns
  resources :yumings
  resources :jiankongs
  resources :feiyongs
  resources :mimas
  resources :fuwus
  resources :apps
  resources :diannaos
  get "/" => redirect("/menus")
  post 'login', :to => 'dengluzhanghus#login'
  get 'upload', :to => 'upload#index'
  post 'upload', :to => 'upload#upload'
  #get '/login' => 'dengluzhanghus#login1', :as => "menus"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/datafile.rb
class Datafile < ActiveRecord::Base  
  def self.save(upload)  
    #name =  upload['datafile'].original_filename  
    directory = "public/data"  
    # create the file path  
    path = File.join(directory, "aaa")  
    # write the file  
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }  
  end  
end  

app/models/diannao.rb
class Diannao < ApplicationRecord
has_and_belongs_to_many :Jiaobenzhixings
has_and_belongs_to_many :kuaisufenfawenjians

accepts_nested_attributes_for :Jiaobenzhixings, allow_destroy: true
def to_s
  mingzi.to_s+"_"+ip.to_s
end
end

app/models/dn.rb
class Dn < ApplicationRecord
end

app/models/feiyong.rb
class Feiyong < ApplicationRecord
end

app/models/fuwu.rb
class Fuwu < ApplicationRecord
end

app/models/huiyuan.rb
class Huiyuan < ApplicationRecord
end

app/models/ipdizhi.rb
class Ipdizhi < ApplicationRecord
end

app/models/jiankong.rb
class Jiankong < ApplicationRecord
end

app/models/kaiguan.rb
class Kaiguan < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :submenu, class_name: "menu",
                          foreign_key: "menu_id"
 
#  belongs_to :pmenu, class_name: "menu"
end

app/models/mima.rb
class Mima < ApplicationRecord
end

app/models/pingguozhanghao.rb
class Pingguozhanghao < ApplicationRecord
end

app/models/shouji.rb
class Shouji < ApplicationRecord
end

app/models/shuabang.rb
class Shuabang < ApplicationRecord
end

app/models/sousuo.rb
class Sousuo < ApplicationRecord
end

app/models/submenu.rb
class Submenu < Menu
end

app/models/tuiguang.rb
class Tuiguang < ApplicationRecord
end

app/models/umeng.rb
class Umeng < ApplicationRecord
end

app/models/wifidn.rb
class Wifidn < ApplicationRecord
end

app/models/yuming.rb
class Yuming < ApplicationRecord
end

app/controllers/pingguozhanghaos_controller.rb
class PingguozhanghaosController < ApplicationController
  before_action :set_pingguozhanghao, only: [:show, :edit, :update, :destroy]

  # GET /pingguozhanghaos
  # GET /pingguozhanghaos.json
  def index
    @pingguozhanghaos = Pingguozhanghao.all
  end

  # GET /pingguozhanghaos/1
  # GET /pingguozhanghaos/1.json
  def show
  end

  # GET /pingguozhanghaos/new
  def new
    @pingguozhanghao = Pingguozhanghao.new
  end

  # GET /pingguozhanghaos/1/edit
  def edit
  end

  # POST /pingguozhanghaos
  # POST /pingguozhanghaos.json
  def create
    @pingguozhanghao = Pingguozhanghao.new(pingguozhanghao_params)

    respond_to do |format|
      if @pingguozhanghao.save
        format.html { redirect_to @pingguozhanghao, notice: 'Pingguozhanghao was successfully created.' }
        format.json { render :show, status: :created, location: @pingguozhanghao }
      else
        format.html { render :new }
        format.json { render json: @pingguozhanghao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pingguozhanghaos/1
  # PATCH/PUT /pingguozhanghaos/1.json
  def update
    respond_to do |format|
      if @pingguozhanghao.update(pingguozhanghao_params)
        format.html { redirect_to @pingguozhanghao, notice: 'Pingguozhanghao was successfully updated.' }
        format.json { render :show, status: :ok, location: @pingguozhanghao }
      else
        format.html { render :edit }
        format.json { render json: @pingguozhanghao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pingguozhanghaos/1
  # DELETE /pingguozhanghaos/1.json
  def destroy
    @pingguozhanghao.destroy
    respond_to do |format|
      format.html { redirect_to pingguozhanghaos_url, notice: 'Pingguozhanghao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pingguozhanghao
      @pingguozhanghao = Pingguozhanghao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pingguozhanghao_params
      params.require(:pingguozhanghao).permit(:zhanghao, :zhanghaomima, :beizhu, :zhuangtai)
    end
end

app/helpers/pingguozhanghaos_helper.rb
module PingguozhanghaosHelper
end

app/views/pingguozhanghaos/_form.html.erb
<%= form_for(pingguozhanghao) do |f| %>
  <% if pingguozhanghao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pingguozhanghao.errors.count, "error") %> prohibited this pingguozhanghao from being saved:</h2>

      <ul>
      <% pingguozhanghao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    账号
    <%= f.text_field :zhanghao %>
  </div>

  <div class="field">
    账号密码
    <%= f.text_field :zhanghaomima %>
  </div>

  <div class="field">
    备注
    <%= f.text_field :beizhu %>
  </div>

  <div class="field">
    状态
    <%= f.text_field :zhuangtai %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pingguozhanghaos/edit.html.erb
<h1>编辑苹果账号</h1>

<%= render 'form', pingguozhanghao: @pingguozhanghao %>

<%= link_to 'Show', @pingguozhanghao %> |
<%= link_to 'Back', pingguozhanghaos_path %>

app/views/pingguozhanghaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>苹果账号</h1>

<table>
  <thead>
    <tr>
      <th>账号</th>
      <th>账号mima</th>
      <th>备注</th>
      <th>状态</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pingguozhanghaos.each do |pingguozhanghao| %>
      <tr>
        <td><%= pingguozhanghao.zhanghao %></td>
        <td><%= pingguozhanghao.zhanghaomima %></td>
        <td><%= pingguozhanghao.beizhu %></td>
        <td><%= pingguozhanghao.zhuangtai %></td>
        <td><%= link_to 'Show', pingguozhanghao %></td>
        <td><%= link_to 'Edit', edit_pingguozhanghao_path(pingguozhanghao) %></td>
        <td><%= link_to 'Destroy', pingguozhanghao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建苹果账号', new_pingguozhanghao_path %>

app/views/pingguozhanghaos/new.html.erb
<h1>新建苹果账号</h1>

<%= render 'form', pingguozhanghao: @pingguozhanghao %>

<%= link_to 'Back', pingguozhanghaos_path %>

app/views/pingguozhanghaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>账号:</strong>
  <%= @pingguozhanghao.zhanghao %>
</p>

<p>
  <strong>账号mima:</strong>
  <%= @pingguozhanghao.zhanghaomima %>
</p>

<p>
  <strong>备注:</strong>
  <%= @pingguozhanghao.beizhu %>
</p>

<p>
  <strong>状态:</strong>
  <%= @pingguozhanghao.zhuangtai %>
</p>

<%= link_to 'Edit', edit_pingguozhanghao_path(@pingguozhanghao) %> |
<%= link_to 'Back', pingguozhanghaos_path %>