config/routes.rb
Rails.application.routes.draw do
  resources :caiwuhuizongs
  resources :jichucanshus
  resources :fengkongcanshus
  resources :tuiguangxiangqings
  resources :xiaoxiliebiaos
  resources :xiaoximobans
  resources :dizhiguanlis
  resources :jiaoseguanlis
  resources :quanxianguanlis
  resources :guanliyuans
  resources :dakuanshibais
  resources :yifangkuans
  resources :xujiedaifangkuanliebiaos
  resources :xinyonghudaifangkuanliebiaos
  resources :tuiguangs
  resources :dianhuahuangyes
  resources :fengxianguanlis
  resources :huiyuans
  resources :lcbzhiyawus
  resources :lcbzhanghus
  resources :kaiguans
  resources :lvmaotongs
  resources :webceshis
  resources :ceshijilus
  resources :pingguoceshis
  resources :anzhuoceshis
  resources :anzhuozidonghuaceshis
  resources :jiaobenzhixings
  resources :esjiaobens
  resources :xitongzhanghuguanlis
  resources :shujukusqlguanlis
  resources :shujukujiaobens
  resources :changyongzuoye1s
  resources :dengluzhanghus
  resources :shujufenxis
  resources :ceshirenwuguanlis
  resources :pingguodingshirenwus
  resources :shujukuzhanghus
  resources :dingshirenwus
  resources :changyongzuoyes
  resources :kuaisuzhixingsqljiaobens
  resources :kuaisufenfawenjians
  resources :kuaisujiaobenzhixings
  resources :pingguozhanghaos
  resources :ipdizhis
  resources :sousuos
  resources :umengs
  resources :shoujis
  resources :shuabangs
  resources :sslzhengshus
  resources :wifidns
  resources :androidupdates
  resources :menus
  resources :menuindices
  resources :peizhiguanlis
  resources :dns
  resources :yumings
  resources :jiankongs
  resources :feiyongs
  resources :mimas
  resources :fuwus
  resources :apps
  resources :diannaos
  get "/" => redirect("/menus")
  post 'login', :to => 'dengluzhanghus#login'
  get 'upload', :to => 'upload#index'
  post 'upload', :to => 'upload#upload'
  #get '/login' => 'dengluzhanghus#login1', :as => "menus"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/datafile.rb
class Datafile < ActiveRecord::Base  
  def self.save(upload)  
    #name =  upload['datafile'].original_filename  
    directory = "public/data"  
    # create the file path  
    path = File.join(directory, "aaa")  
    # write the file  
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }  
  end  
end  

app/models/diannao.rb
class Diannao < ApplicationRecord
has_and_belongs_to_many :Jiaobenzhixings
has_and_belongs_to_many :kuaisufenfawenjians

accepts_nested_attributes_for :Jiaobenzhixings, allow_destroy: true
def to_s
  mingzi.to_s+"_"+ip.to_s
end
end

app/models/dn.rb
class Dn < ApplicationRecord
end

app/models/feiyong.rb
class Feiyong < ApplicationRecord
end

app/models/fengxianguanli.rb
class Fengxianguanli < ApplicationRecord
end

app/models/fuwu.rb
class Fuwu < ApplicationRecord
end

app/models/huiyuan.rb
class Huiyuan < ApplicationRecord
end

app/models/ipdizhi.rb
class Ipdizhi < ApplicationRecord
end

app/models/jiankong.rb
class Jiankong < ApplicationRecord
end

app/models/kaiguan.rb
class Kaiguan < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :submenu, class_name: "menu",
                          foreign_key: "menu_id"
 
#  belongs_to :pmenu, class_name: "menu"
end

app/models/mima.rb
class Mima < ApplicationRecord
end

app/models/shouji.rb
class Shouji < ApplicationRecord
end

app/models/shuabang.rb
class Shuabang < ApplicationRecord
end

app/models/sousuo.rb
class Sousuo < ApplicationRecord
end

app/models/submenu.rb
class Submenu < Menu
end

app/models/tuiguang.rb
class Tuiguang < ApplicationRecord
end

app/models/umeng.rb
class Umeng < ApplicationRecord
end

app/models/wifidn.rb
class Wifidn < ApplicationRecord
end

app/models/yuming.rb
class Yuming < ApplicationRecord
end

app/controllers/fengxianguanlis_controller.rb
class FengxianguanlisController < ApplicationController
  before_action :set_fengxianguanli, only: [:show, :edit, :update, :destroy]

  # GET /fengxianguanlis
  # GET /fengxianguanlis.json
  def index
    @fengxianguanlis = Fengxianguanli.all
  end

  # GET /fengxianguanlis/1
  # GET /fengxianguanlis/1.json
  def show
  end

  # GET /fengxianguanlis/new
  def new
    @fengxianguanli = Fengxianguanli.new
  end

  # GET /fengxianguanlis/1/edit
  def edit
  end

  # POST /fengxianguanlis
  # POST /fengxianguanlis.json
  def create
    @fengxianguanli = Fengxianguanli.new(fengxianguanli_params)

    respond_to do |format|
      if @fengxianguanli.save
        format.html { redirect_to @fengxianguanli, notice: 'Fengxianguanli was successfully created.' }
        format.json { render :show, status: :created, location: @fengxianguanli }
      else
        format.html { render :new }
        format.json { render json: @fengxianguanli.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fengxianguanlis/1
  # PATCH/PUT /fengxianguanlis/1.json
  def update
    respond_to do |format|
      if @fengxianguanli.update(fengxianguanli_params)
        format.html { redirect_to @fengxianguanli, notice: 'Fengxianguanli was successfully updated.' }
        format.json { render :show, status: :ok, location: @fengxianguanli }
      else
        format.html { render :edit }
        format.json { render json: @fengxianguanli.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fengxianguanlis/1
  # DELETE /fengxianguanlis/1.json
  def destroy
    @fengxianguanli.destroy
    respond_to do |format|
      format.html { redirect_to fengxianguanlis_url, notice: 'Fengxianguanli was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fengxianguanli
      @fengxianguanli = Fengxianguanli.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fengxianguanli_params
      params.require(:fengxianguanli).permit(:xingming, :shoujihao, :fenxiandengji, :shuoming)
    end
end

app/helpers/fengxianguanlis_helper.rb
module FengxianguanlisHelper
end

app/views/fengxianguanlis/_form.html.erb
<%= simple_form_for(@fengxianguanli) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :xingming,label:"姓名" %>
    <%= f.input :shoujihao,label:"手机号" %>
    <%= f.input :fenxiandengji,label:"风险等级" %>
    <%= f.input :shuoming,label:"说明" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fengxianguanlis/edit.html.erb
<h1>编辑风险管理</h1>

<%= render 'form', fengxianguanli: @fengxianguanli %>

<%= link_to 'Show', @fengxianguanli %> |
<%= link_to 'Back', fengxianguanlis_path %>

app/views/fengxianguanlis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>风险管理</h1>

<table>
  <thead>
    <tr>
      <th>姓名</th>
      <th>手机号</th>
      <th>风险等级</th>
      <th>说明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fengxianguanlis.each do |fengxianguanli| %>
      <tr>
        <td><%= fengxianguanli.xingming %></td>
        <td><%= fengxianguanli.shoujihao %></td>
        <td><%= fengxianguanli.fenxiandengji %></td>
        <td><%= fengxianguanli.shuoming %></td>
        <td><%= link_to 'Show', fengxianguanli %></td>
        <td><%= link_to 'Edit', edit_fengxianguanli_path(fengxianguanli) %></td>
        <td><%= link_to 'Destroy', fengxianguanli, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建风险管理', new_fengxianguanli_path %>

app/views/fengxianguanlis/new.html.erb
<h1>新建风险管理</h1>

<%= render 'form', fengxianguanli: @fengxianguanli %>

<%= link_to 'Back', fengxianguanlis_path %>

app/views/fengxianguanlis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>姓名:</strong>
  <%= @fengxianguanli.xingming %>
</p>

<p>
  <strong>手机号:</strong>
  <%= @fengxianguanli.shoujihao %>
</p>

<p>
  <strong>风险等级:</strong>
  <%= @fengxianguanli.fenxiandengji %>
</p>

<p>
  <strong>说明:</strong>
  <%= @fengxianguanli.shuoming %>
</p>

<%= link_to 'Edit', edit_fengxianguanli_path(@fengxianguanli) %> |
<%= link_to 'Back', fengxianguanlis_path %>