config/routes.rb
Rails.application.routes.draw do
  resources :caiwuhuizongs
  resources :jichucanshus
  resources :fengkongcanshus
  resources :tuiguangxiangqings
  resources :xiaoxiliebiaos
  resources :xiaoximobans
  resources :dizhiguanlis
  resources :jiaoseguanlis
  resources :quanxianguanlis
  resources :guanliyuans
  resources :dakuanshibais
  resources :yifangkuans
  resources :xujiedaifangkuanliebiaos
  resources :xinyonghudaifangkuanliebiaos
  resources :tuiguangs
  resources :dianhuahuangyes
  resources :fengxianguanlis
  resources :huiyuans
  resources :lcbzhiyawus
  resources :lcbzhanghus
  resources :kaiguans
  resources :lvmaotongs
  resources :webceshis
  resources :ceshijilus
  resources :pingguoceshis
  resources :anzhuoceshis
  resources :anzhuozidonghuaceshis
  resources :jiaobenzhixings
  resources :esjiaobens
  resources :xitongzhanghuguanlis
  resources :shujukusqlguanlis
  resources :shujukujiaobens
  resources :changyongzuoye1s
  resources :dengluzhanghus
  resources :shujufenxis
  resources :ceshirenwuguanlis
  resources :pingguodingshirenwus
  resources :shujukuzhanghus
  resources :dingshirenwus
  resources :changyongzuoyes
  resources :kuaisuzhixingsqljiaobens
  resources :kuaisufenfawenjians
  resources :kuaisujiaobenzhixings
  resources :pingguozhanghaos
  resources :ipdizhis
  resources :sousuos
  resources :umengs
  resources :shoujis
  resources :shuabangs
  resources :sslzhengshus
  resources :wifidns
  resources :androidupdates
  resources :menus
  resources :menuindices
  resources :peizhiguanlis
  resources :dns
  resources :yumings
  resources :jiankongs
  resources :feiyongs
  resources :mimas
  resources :fuwus
  resources :apps
  resources :diannaos
  get "/" => redirect("/menus")
  post 'login', :to => 'dengluzhanghus#login'
  get 'upload', :to => 'upload#index'
  post 'upload', :to => 'upload#upload'
  #get '/login' => 'dengluzhanghus#login1', :as => "menus"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/datafile.rb
class Datafile < ActiveRecord::Base  
  def self.save(upload)  
    #name =  upload['datafile'].original_filename  
    directory = "public/data"  
    # create the file path  
    path = File.join(directory, "aaa")  
    # write the file  
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }  
  end  
end  

app/models/diannao.rb
class Diannao < ApplicationRecord
has_and_belongs_to_many :Jiaobenzhixings
has_and_belongs_to_many :kuaisufenfawenjians

accepts_nested_attributes_for :Jiaobenzhixings, allow_destroy: true
def to_s
  mingzi.to_s+"_"+ip.to_s
end
end

app/models/dn.rb
class Dn < ApplicationRecord
end

app/models/feiyong.rb
class Feiyong < ApplicationRecord
end

app/models/fuwu.rb
class Fuwu < ApplicationRecord
end

app/models/huiyuan.rb
class Huiyuan < ApplicationRecord
end

app/models/ipdizhi.rb
class Ipdizhi < ApplicationRecord
end

app/models/jiankong.rb
class Jiankong < ApplicationRecord
end

app/models/kaiguan.rb
class Kaiguan < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :submenu, class_name: "menu",
                          foreign_key: "menu_id"
 
#  belongs_to :pmenu, class_name: "menu"
end

app/models/mima.rb
class Mima < ApplicationRecord
end

app/models/shouji.rb
class Shouji < ApplicationRecord
end

app/models/shuabang.rb
class Shuabang < ApplicationRecord
end

app/models/shujufenxi.rb
class Shujufenxi < ApplicationRecord
end

app/models/sousuo.rb
class Sousuo < ApplicationRecord
end

app/models/submenu.rb
class Submenu < Menu
end

app/models/tuiguang.rb
class Tuiguang < ApplicationRecord
end

app/models/umeng.rb
class Umeng < ApplicationRecord
end

app/models/wifidn.rb
class Wifidn < ApplicationRecord
end

app/models/yuming.rb
class Yuming < ApplicationRecord
end

app/controllers/shujufenxis_controller.rb
class ShujufenxisController < ApplicationController
  before_action :set_shujufenxi, only: [:show, :edit, :update, :destroy]
  before_action :log
  # GET /shujufenxis
  # GET /shujufenxis.json
  def index
    @shujufenxis = Shujufenxi.all
  end

  # GET /shujufenxis/1
  # GET /shujufenxis/1.json
  def show
  end

  # GET /shujufenxis/new
  def new
    @shujufenxi = Shujufenxi.new
  end

  # GET /shujufenxis/1/edit
  def edit
  end

  # POST /shujufenxis
  # POST /shujufenxis.json
  def create
    @shujufenxi = Shujufenxi.new(shujufenxi_params)

    respond_to do |format|
      if @shujufenxi.save
        format.html { redirect_to @shujufenxi, notice: 'Shujufenxi was successfully created.' }
        format.json { render :show, status: :created, location: @shujufenxi }
      else
        format.html { render :new }
        format.json { render json: @shujufenxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shujufenxis/1
  # PATCH/PUT /shujufenxis/1.json
  def update
    respond_to do |format|
      if @shujufenxi.update(shujufenxi_params)
        format.html { redirect_to @shujufenxi, notice: 'Shujufenxi was successfully updated.' }
        format.json { render :show, status: :ok, location: @shujufenxi }
      else
        format.html { render :edit }
        format.json { render json: @shujufenxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shujufenxis/1
  # DELETE /shujufenxis/1.json
  def destroy
    @shujufenxi.destroy
    respond_to do |format|
      format.html { redirect_to shujufenxis_url, notice: 'Shujufenxi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shujufenxi

      @shujufenxi = Shujufenxi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shujufenxi_params
      params.require(:shujufenxi).permit(:chengxumingcheng, :wangzhi)
    end
end

app/helpers/shujufenxis_helper.rb
module ShujufenxisHelper
end

app/views/shujufenxis/_form.html.erb
<%= form_for(shujufenxi) do |f| %>
  <% if shujufenxi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shujufenxi.errors.count, "error") %> prohibited this shujufenxi from being saved:</h2>

      <ul>
      <% shujufenxi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    程序名称
    <%= f.text_field :chengxumingcheng %>
  </div>

  <div class="field">
    网址
    <%= f.text_area :wangzhi %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shujufenxis/edit.html.erb
<h1>编辑数据分析</h1>

<%= render 'form', shujufenxi: @shujufenxi %>

<%= link_to 'Show', @shujufenxi %> |
<%= link_to 'Back', shujufenxis_path %>

app/views/shujufenxis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>数据分析</h1>

<table>
  <thead>
    <tr>
      <th>程序名称</th>
      <th>网址</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shujufenxis.each do |shujufenxi| %>
      <tr>
        <td><a target=_blank href="<%= shujufenxi.wangzhi %>"><%= shujufenxi.chengxumingcheng %></a></td>
        <td><%= shujufenxi.wangzhi %></td>
        <td><%= link_to 'Show', shujufenxi %></td>
        <td><%= link_to 'Edit', edit_shujufenxi_path(shujufenxi) %></td>
        <td><%= link_to 'Destroy', shujufenxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建数据分析', new_shujufenxi_path %>

app/views/shujufenxis/new.html.erb
<h1>新建数据分析</h1>

<%= render 'form', shujufenxi: @shujufenxi %>

<%= link_to 'Back', shujufenxis_path %>

app/views/shujufenxis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>程序名称:</strong>
  <%= @shujufenxi.chengxumingcheng %>
</p>

<p>
  <strong>网址:</strong>
  <%= @shujufenxi.wangzhi %>
</p>

<%= link_to 'Edit', edit_shujufenxi_path(@shujufenxi) %> |
<%= link_to 'Back', shujufenxis_path %>